
---
server:
  port: 8082

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/navigator?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
            hbm2ddl:
                auto: create
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        database-platform: org.hibernate.dialect.MySQL8Dialect
        
---
